# Generated by Django 5.1.1 on 2025-07-06 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
