# Generated by Django 5.1.1 on 2025-07-06 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderitem_order_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
