GET http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8000/products/?price__range=5,100 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8000/products/?search=Scanner HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8000/products/?ordering=-name HTTP/1.1
Content-Type: application/json

###


POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzM2MjcxLCJpYXQiOjE3NTIzMzU5NzEsImp0aSI6IjQzZjc0YjkwZjNhMzRjOTY5MzFmMjg2NWFkYTU5YjA5IiwidXNlcl9pZCI6Mn0.NdC86TFy9uA1-NIZwxrKDpssFDSkwCQ0WyPoeFfm1Zw

{
    "name": "Product 2",
    "description": "Description 2",
    "price": 100,
    "stock": 100
}

###
GET http://localhost:8000/products/7/ HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/8/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzM2MjcxLCJpYXQiOjE3NTIzMzU5NzEsImp0aSI6IjQzZjc0YjkwZjNhMzRjOTY5MzFmMjg2NWFkYTU5YjA5IiwidXNlcl9pZCI6Mn0.NdC86TFy9uA1-NIZwxrKDpssFDSkwCQ0WyPoeFfm1Zw

{
    "name": "Skywalker",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
DELETE http://localhost:8000/products/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMjE0NzY0LCJpYXQiOjE3NTIyMTQ0NjQsImp0aSI6Ijk2ODc2NGRiYzUyOTQ2MjRhYTc5ZDQ3YWY3NWY5OWE0IiwidXNlcl9pZCI6Mn0.Sz_7mygyq7ktgVmTk_3a_OmMvMLYQ8dALnanleB3GIU


###

GET http://localhost:8000/products/info/ HTTP/1.1
Content-Type: application/json


###

GET http://localhost:8000/products/info/ HTTP/1.1
Content-Type: application/json


###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzkyNDgzLCJpYXQiOjE3NTIzOTIxODMsImp0aSI6ImZmMzVmODk1OWRlODRhMWM5OTQ2MjVlYzhlYjY5NTZkIiwidXNlcl9pZCI6Mn0.E9SvkTcSEHdFDMiIg8_od9Hgla8kfn47BiWEiO5AMfQ

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "obomheire",
    "password": "Secret@123"
    # "username": "admin",
    # "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjI5OTk3MywiaWF0IjoxNzUyMjEzNTczLCJqdGkiOiI5MzVlYmI5N2ZhMjU0ZmU0OThiYTk3ZmNmNjhlNWY1MyIsInVzZXJfaWQiOjF9.NEvesl9vtKKXenUpJB7sjFHyck3jSjZ33A8sVbqVhVU"
}

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzkyNDgzLCJpYXQiOjE3NTIzOTIxODMsImp0aSI6ImZmMzVmODk1OWRlODRhMWM5OTQ2MjVlYzhlYjY5NTZkIiwidXNlcl9pZCI6Mn0.E9SvkTcSEHdFDMiIg8_od9Hgla8kfn47BiWEiO5AMfQ

{
    "status": "Pending",
    "items": [{"product": 1, "quantity": 5}, {"product": 2, "quantity": 8}]
}
###